apiVersion: v1
kind: Pod
metadata:
  name: devwebapp-with-annotations
  labels:
    app: devwebapp-with-annotations
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "devweb-app"
    vault.hashicorp.com/agent-inject-secret-credentials.txt: "secret/data/devwebapp/config"
    vault.hashicorp.com/auth-path: "auth/jwt/location-94999"
    # vault.hashicorp.com/auth-config-path: "auth/jwt/login"
    # vault.hashicorp.com/auth-config-role: "devweb-app"
    # vault.hashicorp.com/auth-type: "jwt"
    #vault.hashicorp.com/agent-pre-populate-only: "false"
    # vault.hashicorp.com/path: "auth/jwt/login"
    # vault.hashicorp.com/auth-type: "jwt"
spec:
  serviceAccountName: default
  containers:
    - name: app
      image: burtlo/devwebapp-ruby:k8s
      # env:
      # - name: VAULT_ADDR
      #   value: "http://external-vault:8200"
      # - name: VAULT_TOKEN
      #   value: root